-- Phase 4: private planning pins.
--
-- The highest-risk feature in the account project. A mistake here leaks where a
-- named person plans to sleep alone outdoors. Everything below is shaped around
-- making that hard rather than making the code short.
--
-- WHY A SEPARATE TABLE, NOT A `visibility` COLUMN ON `spots`
--
-- The original plan said to add `visibility` to `spots`. That is the wrong
-- shape:
--
--   1. A separate table CANNOT leak into the public map. Private pins never
--      enter the query that draws it. With a visibility column, every existing
--      query — map, search, admin panel, GPX export, spots-private — becomes a
--      place where forgetting one filter exposes them. Eight chances to be
--      wrong forever, against zero.
--   2. The lifecycles share nothing. A public spot is submitted, moderated,
--      approved, flagged, soft-deleted. A planning pin is created and deleted by
--      one person. Sharing a table means carrying status, flags and
--      flag_reports on rows where they are meaningless.
--   3. The policy the map depends on is never edited, so there is no version of
--      this change that empties the map.
--
-- WHY ACCOUNT ONLY, WITH NO DEVICE-TOKEN FALLBACK
--
-- owner_token is generated by the browser and unverifiable by the server. It is
-- adequate for "these are probably your spots" and useless as a privacy
-- boundary — anyone holding a token can use it. Privacy here has to rest on
-- auth.uid(), which Supabase signs.

create table if not exists planning_pins (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users(id) on delete cascade,
  name       text not null check (char_length(trim(name)) between 1 and 80),
  note       text check (char_length(note) <= 500),
  latitude   double precision not null check (latitude between -90 and 90),
  longitude  double precision not null check (longitude between -180 and 180),
  created_at timestamptz not null default now()
);

create index if not exists planning_pins_user_idx on planning_pins (user_id);

alter table planning_pins enable row level security;

-- Every policy is auth.uid() = user_id, including the insert check — without it
-- a signed-in user could write rows attributed to someone else.
drop policy if exists "own planning pins read" on planning_pins;
create policy "own planning pins read" on planning_pins
  for select using (auth.uid() = user_id);

drop policy if exists "own planning pins insert" on planning_pins;
create policy "own planning pins insert" on planning_pins
  for insert with check (auth.uid() = user_id);

drop policy if exists "own planning pins update" on planning_pins;
create policy "own planning pins update" on planning_pins
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own planning pins delete" on planning_pins;
create policy "own planning pins delete" on planning_pins
  for delete using (auth.uid() = user_id);

-- Supabase grants new public-schema tables to anon and authenticated by
-- DEFAULT, so granting to authenticated restricts nothing. Revoking anon is the
-- part that matters — it stops the request before RLS is consulted, and means
-- the privacy of this table does not rest on a single mechanism.
--
-- This was found the hard way on `favourites` an hour before this file was
-- written: anon held SELECT, INSERT and DELETE there and only RLS was stopping
-- it.
revoke all on planning_pins from anon;
grant select, insert, update, delete on planning_pins to authenticated;

-- ---------------------------------------------------------------------------
-- VERIFY — and verify with a ROW PRESENT.
--
-- An empty table returns [] whether RLS is working or not, so probing before
-- creating a pin proves nothing. Likewise a DELETE returning 204 is not
-- evidence: PostgREST returns 204 whether it deleted rows or matched none.
-- Both mistakes were made today.
--
--   1. Create a pin in the app while signed in.
--   2. select count(*) from planning_pins;          -- must be >= 1
--   3. With the ANON key, every one of these must be 401 / 42501:
--        GET    /rest/v1/planning_pins?select=*
--        POST   /rest/v1/planning_pins
--        DELETE /rest/v1/planning_pins?id=neq.<random uuid>
--   4. As a SECOND signed-in user, GET /rest/v1/planning_pins must return []
--      — that is the test that anon cannot perform, and the one that matters.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- ROLLBACK
-- ---------------------------------------------------------------------------
-- drop table if exists planning_pins;
