// Reads that must not be answerable with the public anon key.
//
// WHY
//
// RLS on `spots` still carries "Allow public reads" USING (true), so every
// pending and soft-deleted row is readable by anyone holding the anon key —
// which ships in the JS bundle by design. Dropping that policy is the goal, but
// three legitimate reads depend on it and have to move here first:
//
//   admin-all      the admin panel, every spot whatever its status
//   admin-pending  the admin's pending queue
//   mine-pending   a user seeing their OWN submission awaiting approval
//
// Once this is deployed and the client uses it, the policy can be dropped and
// pending spots stop being publicly browsable.
//
// ON `mine-pending` AND owner_token
//
// This is not an admin path and it cannot be secured like one. owner_token is
// generated by the browser and stored in localStorage; the server has no way to
// verify the caller is who the token says. So the trust model is unchanged from
// today — anyone holding a token can already edit and delete those spots.
//
// What DOES change is that pending spots stop being enumerable. Today anyone
// can list every pending submission on the site; afterwards you need a specific
// valid token and you see only that device's own.
//
// It becomes a real boundary in Phase 1, when auth.uid() replaces the token.
// See docs/accounts.md.

import { createClient } from '@supabase/supabase-js'
import { verifyToken } from './_admin-auth.js'
import { verifiedUserId } from './_owner.js'
import { SPOT_COLUMNS_SQL } from './_spot-columns.js'

const supabaseAdmin = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
)

// Same floor as my_spot_ids(): refuse to answer for trivially short guesses, so
// this cannot be used to fish for spots by trying values.
const MIN_TOKEN_LENGTH = 20

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end()
  const { scope, admin_token, owner_token } = req.body || {}

  // This query bypasses RLS, so the column list is the only thing keeping
  // owner_token out of the response. Never widen it to '*'.
  const base = () => supabaseAdmin.from('spots').select(SPOT_COLUMNS_SQL)

  if (scope === 'admin-all' || scope === 'admin-pending') {
    if (!verifyToken(admin_token)) return res.status(403).json({ error: 'Forbidden' })

    // user_id is added only for admin scopes, never for mine-pending — the
    // admin needs to know who contributed what, and no other caller does.
    const adminBase = () => supabaseAdmin.from('spots').select(`${SPOT_COLUMNS_SQL}, user_id`)
    const query = scope === 'admin-all'
      ? adminBase().order('created_at', { ascending: false })
      : adminBase().eq('status', 'pending').is('deleted_at', null)

    const { data, error } = await query
    if (error) return res.status(500).json({ error: 'Query failed' })
    return res.status(200).json({ spots: data ?? [] })
  }

  // Contributors, for the admin panel: who they are, what they chose to be
  // called, and how much they have added.
  //
  // Reads auth.users and profiles with the SERVICE ROLE rather than by relaxing
  // RLS. That distinction is the whole reason the app can honestly tell users
  // their name is not visible to other users: no policy exposes it, and the only
  // way in is a server-side endpoint behind an admin token.
  //
  // Email is the identity here because it is the one thing every account has —
  // a display name is optional and may be absent, which is what "Anonym" means
  // in this list.
  if (scope === 'admin-users') {
    if (!verifyToken(admin_token)) return res.status(403).json({ error: 'Forbidden' })

    const [{ data: userList, error: userErr }, { data: profiles }, { data: owned }] =
      await Promise.all([
        supabaseAdmin.auth.admin.listUsers({ page: 1, perPage: 1000 }),
        supabaseAdmin.from('profiles').select('user_id, username'),
        supabaseAdmin.from('spots').select('user_id, status, deleted_at').not('user_id', 'is', null),
      ])
    if (userErr) return res.status(500).json({ error: 'Query failed' })

    const nameById = new Map((profiles ?? []).map((p) => [p.user_id, p.username]))
    const counts = new Map()
    for (const s of owned ?? []) {
      const c = counts.get(s.user_id) ?? { total: 0, approved: 0, pending: 0, deleted: 0 }
      c.total++
      if (s.deleted_at) c.deleted++
      else if (s.status === 'approved') c.approved++
      else if (s.status === 'pending') c.pending++
      counts.set(s.user_id, c)
    }

    const users = (userList?.users ?? []).map((u) => ({
      id: u.id,
      email: u.email,
      username: nameById.get(u.id) ?? null, // null renders as "Anonym"
      created_at: u.created_at,
      last_sign_in_at: u.last_sign_in_at,
      spots: counts.get(u.id) ?? { total: 0, approved: 0, pending: 0, deleted: 0 },
    }))
    users.sort((a, b) => b.spots.total - a.spots.total)

    return res.status(200).json({ users })
  }

  if (scope === 'mine-pending') {
    // Account OR device token, so a signed-in user sees a pending spot from any
    // device, and someone who never signed in still sees theirs. See _owner.js.
    const userId = await verifiedUserId(req)
    const hasToken = typeof owner_token === 'string' && owner_token.length >= MIN_TOKEN_LENGTH
    if (!userId && !hasToken) return res.status(200).json({ spots: [] })

    // Two queries rather than PostgREST's .or(), which takes a filter STRING —
    // interpolating a client-supplied token into it would let a value like
    // "x,user_id.not.is.null" rewrite the filter and return every pending spot
    // on the site. .eq() passes the value as a parameter, so it cannot.
    const pending = () => base().eq('status', 'pending').is('deleted_at', null)
    const [byUser, byToken] = await Promise.all([
      userId ? pending().eq('user_id', userId) : Promise.resolve({ data: [] }),
      hasToken ? pending().eq('owner_token', owner_token) : Promise.resolve({ data: [] }),
    ])
    if (byUser.error || byToken.error) return res.status(500).json({ error: 'Query failed' })

    const merged = new Map()
    for (const s of [...(byUser.data ?? []), ...(byToken.data ?? [])]) merged.set(s.id, s)
    return res.status(200).json({ spots: [...merged.values()] })
  }

  return res.status(400).json({ error: 'Unknown scope' })
}
