// Reads that must not be answerable with the public anon key.
//
// WHY
//
// RLS on `spots` still carries "Allow public reads" USING (true), so every
// pending and soft-deleted row is readable by anyone holding the anon key —
// which ships in the JS bundle by design. Dropping that policy is the goal, but
// three legitimate reads depend on it and have to move here first:
//
//   admin-all      the admin panel, every spot whatever its status
//   admin-pending  the admin's pending queue
//   mine-pending   a user seeing their OWN submission awaiting approval
//
// Once this is deployed and the client uses it, the policy can be dropped and
// pending spots stop being publicly browsable.
//
// ON `mine-pending` AND owner_token
//
// This is not an admin path and it cannot be secured like one. owner_token is
// generated by the browser and stored in localStorage; the server has no way to
// verify the caller is who the token says. So the trust model is unchanged from
// today — anyone holding a token can already edit and delete those spots.
//
// What DOES change is that pending spots stop being enumerable. Today anyone
// can list every pending submission on the site; afterwards you need a specific
// valid token and you see only that device's own.
//
// It becomes a real boundary in Phase 1, when auth.uid() replaces the token.
// See docs/accounts.md.

import { createClient } from '@supabase/supabase-js'
import { verifyToken } from './_admin-auth.js'
import { SPOT_COLUMNS_SQL } from './_spot-columns.js'

const supabaseAdmin = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
)

// Same floor as my_spot_ids(): refuse to answer for trivially short guesses, so
// this cannot be used to fish for spots by trying values.
const MIN_TOKEN_LENGTH = 20

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end()
  const { scope, admin_token, owner_token } = req.body || {}

  // This query bypasses RLS, so the column list is the only thing keeping
  // owner_token out of the response. Never widen it to '*'.
  const base = () => supabaseAdmin.from('spots').select(SPOT_COLUMNS_SQL)

  if (scope === 'admin-all' || scope === 'admin-pending') {
    if (!verifyToken(admin_token)) return res.status(403).json({ error: 'Forbidden' })

    const query = scope === 'admin-all'
      ? base().order('created_at', { ascending: false })
      : base().eq('status', 'pending').is('deleted_at', null)

    const { data, error } = await query
    if (error) return res.status(500).json({ error: 'Query failed' })
    return res.status(200).json({ spots: data ?? [] })
  }

  if (scope === 'mine-pending') {
    if (typeof owner_token !== 'string' || owner_token.length < MIN_TOKEN_LENGTH) {
      return res.status(200).json({ spots: [] })
    }
    const { data, error } = await base()
      .eq('owner_token', owner_token)
      .eq('status', 'pending')
      .is('deleted_at', null)
    if (error) return res.status(500).json({ error: 'Query failed' })
    return res.status(200).json({ spots: data ?? [] })
  }

  return res.status(400).json({ error: 'Unknown scope' })
}
